services:
  - type: web
    name: aacs-server
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install && npx playwright install chromium --with-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7777
      - key: MONGODB_URI
        value: mongodb+srv://simple-crud:0TxCL5jZ9DIMozhh@ccluster0.5pxwvij.mongodb.net/devengers-aacs2?retryWrites=true&w=majority
      - key: REDIS_HOST
        value: main-gar-180745.upstash.io
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: gQAAAAAAAsIJAAIgcDI0ZDViY2QzYWYzNzc0NWNjYmIzMDE3MzRlMmM4ZDk4Ng
      - key: GITHUB_TOKEN
        value: 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
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6K5Rl6LGKdVN_16ca8hKk1l3pXee64_HDGuBocStkDSjA
      - key: CLIENT_URL
        value: https://aacs-client.vercel.app
